# Generated by Django 6.0.6 on 2026-09-26 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_place_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('attraction', 'Attraction'), ('transport', 'Transport'), ('beach', 'Beach'), ('nature', 'Nature'), ('activity', 'Activity'), ('misc', 'Miscellaneous')], default='misc', max_length=50)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_place_id'], name='trips_place_externa_21e316_idx'), models.Index(fields=['name'], name='trips_place_name_bee072_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('travel_style', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips_db', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='trips.trip')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('distance', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('transport_mode', models.CharField(choices=[('driving', 'Driving'), ('walking', 'Walking'), ('bicycle', 'Bicycle'), ('two_wheeler', 'Two Wheeler'), ('transit', 'Transit')], default='driving', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Hotel', 'Hotel'), ('Food', 'Food'), ('Activity', 'Activity'), ('Entry Fee', 'Entry Fee'), ('Local Transport', 'Local Transport'), ('Parking', 'Parking'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('ESTIMATED', 'Estimated'), ('USER_PROVIDED', 'User Provided')], default='ESTIMATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField(blank=True, default='')),
                ('provider', models.CharField(choices=[('GEMINI', 'GEMINI'), ('GROQ', 'GROQ')], default='GEMINI', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('start_time', models.CharField(blank=True, default='', max_length=20)),
                ('end_time', models.CharField(blank=True, default='', max_length=20)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travel_time_from_previous', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.itineraryday')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='trips.place')),
            ],
            options={
                'ordering': ['sequence_order', 'start_time'],
                'indexes': [models.Index(fields=['itinerary_day', 'sequence_order'], name='trips_itine_itinera_457c98_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'created_at'], name='trips_trip_user_id_76cc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'destination'], name='trips_trip_user_id_77f4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['destination', 'start_date'], name='trips_trip_destina_6bd4c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='trip_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_travelers__gte', 1)), name='trip_traveler_count_positive'),
        ),
        migrations.AlterUniqueTogether(
            name='savedtrip',
            unique_together={('user', 'trip')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['trip', 'transport_mode'], name='trips_route_trip_id_b0db96_idx'),
        ),
        migrations.AddIndex(
            model_name='itineraryday',
            index=models.Index(fields=['trip', 'day_number'], name='trips_itine_trip_id_3404ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('trip', 'day_number')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['trip', 'category'], name='trips_expen_trip_id_0d9b86_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'trip'], name='trips_expen_user_id_43a126_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['user', 'trip', 'created_at'], name='trips_aicon_user_id_e37726_idx'),
        ),
    ]
