# Generated by Django 6.0.6 on 2026-09-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='action',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
