# Generated by Django 6.0.6 on 2026-09-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_aiconversation_action_aiconversation_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='photo_reference',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
