# Generated by Django 6.0.5 on 2026-05-06 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('budget_category', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('highlights', models.TextField(blank=True)),
                ('estimated_cost', models.CharField(blank=True, max_length=100)),
                ('best_time', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('group_type', models.CharField(max_length=50)),
                ('travel_scope', models.CharField(max_length=50)),
                ('num_days', models.IntegerField()),
                ('food_preference', models.CharField(blank=True, max_length=100)),
                ('accommodation', models.CharField(blank=True, max_length=100)),
                ('departure_location', models.CharField(max_length=200)),
                ('travel_medium', models.CharField(max_length=100)),
                ('destination_style', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_spots', models.TextField(blank=True)),
                ('local_food', models.TextField(blank=True)),
                ('transport_info', models.TextField(blank=True)),
                ('accommodation_options', models.TextField(blank=True)),
                ('travel_tips', models.TextField(blank=True)),
                ('emergency_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='recommendations.triprecommendation')),
            ],
        ),
        migrations.AddField(
            model_name='triprecommendation',
            name='trip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.triprequest'),
        ),
    ]
